version: '3'
services:
  app:
    build: app/
    ports:
      - "3000:3000"
  testservice:
    build: test-service/
    ports:
      - "3010:3010"
  users:
    build: users-service/
    ports:
      - "3020:3020"
  gateway:
    build: envoy/
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"